name: Build Website

on:
  push:
    branches:
      - main
      - feature/forgot-password
    #tags:
    #  - 'build_*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '22'  # idk

    - name: Install dependencies
      run: |
        npm install

    - name: Build Website 
      run: | # 2>/dev/null to ignore warnings
        npm run build 2>/dev/null

    - name: Create a tag
      id: create_tag
      run: |
        COMMIT_HASH=$(git rev-parse --short HEAD)  #
        TAG_NAME="build_${{ github.run_number }}-${COMMIT_HASH}"  
        git tag $TAG_NAME
        git push origin $TAG_NAME
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Create a GitHub release
      id: release
      uses: softprops/action-gh-release@v1
      with:
        files: 'dist/**/*'  
        tag_name: $TAG_NAME
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  