name: Build Website

on:
  push:
    branches:
      - main 
      - feature/forgot-password

jobs:
  auto-tag:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Create a tag
        id: create_tag
        run: |
          COMMIT_HASH=$(git rev-parse --short HEAD)  #
          TAG_NAME="build_${{ github.run_number }}-${COMMIT_HASH}"  
          git tag $TAG_NAME
          git push origin $TAG_NAME
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}